# Generated by Django 6.0.2 on 2026-03-04 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_stream'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='rollno',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
