# Generated by Django 6.0.2 on 2026-03-04 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_rollno'),
    ]

    def assign_rollnos(apps, schema_editor):
        CustomUser = apps.get_model('accounts', 'CustomUser')
        # clear roll numbers for non-students to avoid conflicts
        CustomUser.objects.exclude(role='student').update(rollno=None)
        # generate sequential roll numbers for students starting at 1
        students = list(CustomUser.objects.filter(role='student').order_by('id'))
        next_roll = 1
        used = set()
        # compute frequencies of existing rollnos among students
        freq = {}
        for stu in students:
            if stu.rollno is not None:
                freq[stu.rollno] = freq.get(stu.rollno, 0) + 1
                used.add(stu.rollno)
                if stu.rollno >= next_roll:
                    next_roll = stu.rollno + 1
        # now assign to those missing or duplicated
        for stu in students:
            if stu.rollno is None or (stu.rollno is not None and freq.get(stu.rollno, 0) > 1):
                # if duplicate remove one frequency count
                if stu.rollno is not None and freq.get(stu.rollno, 0) > 1:
                    freq[stu.rollno] -= 1
                # find next unused number
                while next_roll in used:
                    next_roll += 1
                stu.rollno = next_roll
                stu.save()
                used.add(next_roll)
                next_roll += 1

    def reverse_func(apps, schema_editor):
        # no reverse action
        pass

    operations = [
        migrations.RunPython(assign_rollnos, reverse_func),
    ]
