# Generated by Django 6.0.2 on 2026-03-04 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_assign_roll_numbers'),
    ]

    def clean_rollnos(apps, schema_editor):
        CustomUser = apps.get_model('accounts', 'CustomUser')
        # clear roll numbers for non-students
        CustomUser.objects.exclude(role='student').update(rollno=None)
        # assign sequential numbers to all students (1,2,3,... by id)
        students = CustomUser.objects.filter(role='student').order_by('id')
        for idx, stu in enumerate(students, start=1):
            if stu.rollno != idx:
                stu.rollno = idx
                stu.save()

    operations = [
        migrations.RunPython(clean_rollnos, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='customuser',
            name='rollno',
            field=models.PositiveIntegerField(blank=True, null=True, unique=True),
        ),
    ]
