# Generated by Django 6.0.2 on 2026-03-04 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_enforce_unique_rollno'),
    ]

    def resequence(apps, schema_editor):
        CustomUser = apps.get_model('accounts', 'CustomUser')
        students = CustomUser.objects.filter(role='student').order_by('id')
        for idx, stu in enumerate(students, start=1):
            if stu.rollno != idx:
                stu.rollno = idx
                stu.save()

    operations = [
        migrations.RunPython(resequence, migrations.RunPython.noop),
    ]
