# Generated by Django 6.0.3 on 2026-03-23 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_resequence_rollno'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='stream',
            field=models.CharField(choices=[('Commerce', 'Commerce'), ('Science', 'Science'), ('Arts', 'Arts'), ('BCA', 'BCA'), ('B.Tech', 'B.Tech')], default='Science', max_length=30),
        ),
    ]
