# Generated by Django 6.0.3 on 2026-03-23 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0004_alter_attendance_status_leaverequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='semester',
            field=models.PositiveSmallIntegerField(choices=[(1, '1st'), (2, '2nd'), (3, '3rd'), (4, '4th'), (5, '5th'), (6, '6th'), (7, '7th'), (8, '8th')], default=1, help_text='Semester during which attendance was recorded'),
        ),
    ]
